'''
Modify the starter code below to create your own cool drawing
and then Pull Request it to your instructor. Make sure you
keep the last two lines of code. Your first and last name must be written on your art.
The last line keeps the window open until you click to close.

Turtle Documentation: https://docs.python.org/3.3/library/turtle.html?highlight=turtle

'''
import turtle
walle=turtle.Turtle()
screen=turtle.Screen() # makes a screen object
screen.bgcolor('white') # colors the screen
walle.pensize(3) # width of pen line
walle.speed(15)  # speed of drawing. Go fast to not waste time.

walle.color('black')           # Line 17-34 = tread black
walle.penup()
walle.goto(-90, -90)
walle.begin_fill()
walle.pendown()
walle.goto(-90, -25)
walle.goto(-50, -25)
walle.goto(-50, -90)
walle.goto(-90, -90)
walle.penup()
walle.goto(90, -90)
walle.pendown()
walle.goto(90, -25)
walle.goto(50, -25)
walle.goto(50, -90)
walle.goto(90, -90)
walle.end_fill()
walle.penup()

walle.color('grey')            # Line 36-228 = tread grey
walle.goto(-90, -80)
walle.pendown()
walle.goto(-75, -80)
walle.penup()
walle.goto(-71, -80)
walle.pendown()
walle.goto(-69, -80)
walle.penup()
walle.goto(-65, -80)
walle.pendown()
walle.goto(-50, -80)
walle.penup()
walle.goto(-90, -71)
walle.pendown()
walle.goto(-75, -71)
walle.penup()
walle.goto(-71, -71)
walle.pendown()
walle.goto(-69, -71)
walle.penup()
walle.goto(-65, -71)
walle.pendown()
walle.goto(-50, -71)
walle.penup()
walle.goto(-90, -62)
walle.pendown()
walle.goto(-75, -62)
walle.penup()
walle.goto(-71, -62)
walle.pendown()
walle.goto(-69, -62)
walle.penup()
walle.goto(-65, -62)
walle.pendown()
walle.goto(-50, -62)
walle.penup()
walle.goto(-90, -54)
walle.pendown()
walle.goto(-75, -54)
walle.penup()
walle.goto(-71, -54)
walle.pendown()
walle.goto(-69, -54)
walle.penup()
walle.goto(-65, -54)
walle.pendown()
walle.goto(-50, -54)
walle.penup()
walle.goto(-90, -46)
walle.pendown()
walle.goto(-75, -46)
walle.penup()
walle.goto(-71, -46)
walle.pendown()
walle.goto(-69, -46)
walle.penup()
walle.goto(-65, -46)
walle.pendown()
walle.goto(-50, -46)
walle.penup()
walle.goto(-90, -39)
walle.pendown()
walle.goto(-75, -39)
walle.penup()
walle.goto(-71, -39)
walle.pendown()
walle.goto(-69, -39)
walle.penup()
walle.goto(-65, -39)
walle.pendown()
walle.goto(-50, -39)
walle.penup()
walle.goto(-90, -33)
walle.pendown()
walle.goto(-75, -33)
walle.penup()
walle.goto(-71, -33)
walle.pendown()
walle.goto(-69, -33)
walle.penup()
walle.goto(-65, -33)
walle.pendown()
walle.goto(-50, -33)
walle.penup()
walle.goto(-90, -27)
walle.pendown()
walle.goto(-75, -27)
walle.penup()
walle.goto(-71, -27)
walle.pendown()
walle.goto(-69, -27)
walle.penup()
walle.goto(-65, -27)
walle.pendown()
walle.goto(-50, -27)
walle.penup()
walle.goto(90, -80)
walle.pendown()
walle.goto(75, -80)
walle.penup()
walle.goto(71, -80)
walle.pendown()
walle.goto(69, -80)
walle.penup()
walle.goto(65, -80)
walle.pendown()
walle.goto(50, -80)
walle.penup()
walle.goto(90, -71)
walle.pendown()
walle.goto(75, -71)
walle.penup()
walle.goto(71, -71)
walle.pendown()
walle.goto(69, -71)
walle.penup()
walle.goto(65, -71)
walle.pendown()
walle.goto(50, -71)
walle.penup()
walle.goto(90, -62)
walle.pendown()
walle.goto(75, -62)
walle.penup()
walle.goto(71, -62)
walle.pendown()
walle.goto(69, -62)
walle.penup()
walle.goto(65, -62)
walle.pendown()
walle.goto(50, -62)
walle.penup()
walle.goto(90, -54)
walle.pendown()
walle.goto(75, -54)
walle.penup()
walle.goto(71, -54)
walle.pendown()
walle.goto(69, -54)
walle.penup()
walle.goto(65, -54)
walle.pendown()
walle.goto(50, -54)
walle.penup()
walle.goto(90, -46)
walle.pendown()
walle.goto(75, -46)
walle.penup()
walle.goto(71, -46)
walle.pendown()
walle.goto(69, -46)
walle.penup()
walle.goto(65, -46)
walle.pendown()
walle.goto(50, -46)
walle.penup()
walle.goto(90, -39)
walle.pendown()
walle.goto(75, -39)
walle.penup()
walle.goto(71, -39)
walle.pendown()
walle.goto(69, -39)
walle.penup()
walle.goto(65, -39)
walle.pendown()
walle.goto(50, -39)
walle.penup()
walle.goto(90, -33)
walle.pendown()
walle.goto(75, -33)
walle.penup()
walle.goto(71, -33)
walle.pendown()
walle.goto(69, -33)
walle.penup()
walle.goto(65, -33)
walle.pendown()
walle.goto(50, -33)
walle.penup()
walle.goto(90, -27)
walle.pendown()
walle.goto(75, -27)
walle.penup()
walle.goto(71, -27)
walle.pendown()
walle.goto(69, -27)
walle.penup()
walle.goto(65, -27)
walle.pendown()
walle.goto(50, -27)
walle.penup()

walle.begin_fill()             # Line 230-252 = tread body connector
walle.goto(-47, -70)
walle.pendown()
walle.goto(-35, -70)
walle.goto(-35, -47)
walle.goto(-30, -47)
walle.goto(-30, -57)
walle.goto(-47, -57)
walle.goto(-47, -70)
walle.goto(-47, -70)
walle.end_fill()
walle.penup()
walle.goto(47, -70)
walle.begin_fill()
walle.pendown()
walle.goto(35, -70)
walle.goto(35, -47)
walle.goto(30, -47)
walle.goto(30, -57)
walle.goto(47, -57)
walle.goto(47, -70)
walle.end_fill()
walle.penup()

walle.color('orange')          # line 254-262 = body orange
walle.goto(47, -50)
walle.begin_fill()
walle.pendown()
walle.goto(-47, -50)
walle.goto(-47, 20)
walle.goto(47, 20)
walle.goto(47, -50)
walle.end_fill()
walle.penup()

walle.color('gray')            # line 265-274 = body grey
walle.goto(47, 20)
walle.begin_fill()
walle.pendown()
walle.goto(-47, 20)
walle.goto(-47, 60)
walle.goto(47, 60)
walle.goto(47, 20)
walle.end_fill()
walle.penup()

walle.goto(50, 35)             # line - = right arm
walle.color('orange')
walle.begin_fill()
walle.pendown()
walle.goto(67, 35)
walle.goto(67, 28)
walle.goto(50, 28)
walle.goto(50, 35)
walle.end_fill()
walle.penup()
walle.goto(65, 28)
walle.color('gray')
walle.begin_fill()
walle.pendown()
walle.circle(3)
walle.end_fill()
walle.penup()
walle.goto(53, 30)
walle.begin_fill()
walle.pendown()
walle.goto(63, 30)
walle.goto(63, 10)
walle.goto(53, 10)
walle.goto(53, 30)
walle.end_fill()
walle.penup()
walle.goto(67, 30)
walle.begin_fill()
walle.pendown()
walle.goto(77, 30)
walle.goto(77, 10)
walle.goto(67, 10)
walle.goto(67, 30)
walle.end_fill()
walle.penup()

walle.goto(-53, 35)            # line - = left arm
walle.color('orange')
walle.begin_fill()
walle.pendown()
walle.goto(-67, 35)
walle.goto(-67, 28)
walle.goto(-50, 28)
walle.goto(-50, 35)
walle.end_fill()
walle.penup()
walle.goto(-53, 30)
walle.color('gray')
walle.begin_fill()
walle.pendown()
walle.goto(-63, 30)
walle.goto(-63, 25)
walle.goto(-53, 25)
walle.goto(-53, 30)
walle.end_fill()
walle.penup()
walle.goto(-67, 30)
walle.begin_fill()
walle.pendown()
walle.goto(-77, 30)
walle.goto(-77, 25)
walle.goto(-67, 25)
walle.goto(-67, 30)
walle.end_fill()
walle.penup()
walle.goto(-60, 32)
walle.begin_fill()
walle.pendown()
walle.goto(-70, 32)
walle.goto(-70, 52)
walle.goto(-60, 52)
walle.goto(-60, 32)
walle.end_fill()
walle.penup()

walle.goto(-75, 30)            # line - = Rubiks Cube
walle.color('black')
walle.begin_fill()
walle.pendown()
walle.goto(-55, 30)
walle.goto(-55, 50)
walle.goto(-75, 50)
walle.goto(-75, 30)
walle.end_fill()
walle.penup()
walle.goto(-73, 32)
walle.pensize(1)
walle.color('blue')
walle.begin_fill()
walle.pendown()
walle.goto(-69, 32)
walle.goto(-69, 36)
walle.goto(-73, 36)
walle.goto(-73, 32)
walle.penup()
walle.goto(-67, 32)
walle.pendown()
walle.goto(-63, 32)
walle.goto(-63, 36)
walle.goto(-67, 36)
walle.goto(-67, 32)
walle.end_fill()
walle.penup()
walle.color('white')
walle.goto(-61, 32)
walle.begin_fill()
walle.pendown()
walle.goto(-57, 32)
walle.goto(-57, 36)
walle.goto(-61, 36)
walle.goto(-61, 32)
walle.end_fill()
walle.penup()
walle.goto(-73, 38)
walle.begin_fill()
walle.pendown()
walle.goto(-69, 38)
walle.goto(-69, 42)
walle.goto(-73, 42)
walle.goto(-73, 38)
walle.penup()
walle.goto(-73, 44)
walle.pendown()
walle.goto(-69, 44)
walle.goto(-69, 48)
walle.goto(-73, 48)
walle.goto(-73, 44)
walle.end_fill()
walle.penup()
walle.goto(-61, 44)
walle.begin_fill()
walle.pendown()
walle.goto(-57, 44)
walle.goto(-57, 48)
walle.goto(-61, 48)
walle.goto(-61, 44)
walle.end_fill()
walle.penup()
walle.color('red')
walle.goto(-67, 44)
walle.begin_fill()
walle.pendown()
walle.goto(-63, 44)
walle.goto(-63, 48)
walle.goto(-67, 48)
walle.goto(-67, 44)
walle.penup()
walle.goto(-67, 38)
walle.pendown()
walle.goto(-63, 38)
walle.goto(-63, 42)
walle.goto(-67, 42)
walle.goto(-67, 38)
walle.end_fill()
walle.penup()
walle.goto(-61, 38)
walle.begin_fill()
walle.pendown()
walle.goto(-57, 38)
walle.goto(-57, 42)
walle.goto(-61, 42)
walle.goto(-61, 38)
walle.end_fill()
walle.penup()

walle.color('black')           # line - = body display
walle.goto(-20, 45)
walle.begin_fill()
walle.pendown()
walle.goto(-20, 55)
walle.goto(-5, 55)
walle.goto(-5, 45)
walle.goto(-20, 45)
walle.end_fill()
walle.penup()
walle.goto(-20, 30)
walle.begin_fill()
walle.pendown()
walle.goto(-20, 35)
walle.goto(-15, 35)
walle.goto(-15, 30)
walle.goto(-20, 30)
walle.end_fill()
walle.penup()
walle.goto(-18, 32)
walle.color('red')
walle.begin_fill()
walle.pendown()
walle.circle(.5)
walle.end_fill()
walle.penup()
walle.goto(5, 28)
walle.color('black')
walle.begin_fill()
walle.pendown()
walle.goto(21, 28)
walle.goto(21, 56)
walle.goto(5, 56)
walle.goto(5, 28)
walle.end_fill()
walle.penup()
walle.color('yellow')
walle.pensize(1)
walle.goto(15, 30)
walle.pendown()
walle.goto(20, 30)
walle.penup()
walle.goto(15, 33)
walle.pendown()
walle.goto(20, 33)
walle.penup()
walle.goto(15, 36)
walle.pendown()
walle.goto(20, 36)
walle.penup()
walle.goto(15, 39)
walle.pendown()
walle.goto(20, 39)
walle.penup()
walle.goto(15, 42)
walle.pendown()
walle.goto(20, 42)
walle.penup()
walle.goto(15, 45)
walle.pendown()
walle.goto(20, 45)
walle.penup()
walle.goto(15, 48)
walle.pendown()
walle.goto(20, 48)
walle.penup()
walle.goto(15, 51)
walle.pendown()
walle.goto(20, 51)
walle.penup()
walle.goto(15, 54)
walle.pendown()
walle.goto(20, 54)
walle.penup()
walle.goto(7, 50)
walle.begin_fill()
walle.pendown()
walle.circle(1.5)
walle.end_fill()
walle.penup()

walle.pensize(3)               # line - = neck
walle.color('orange')
walle.goto(-5, 61)
walle.begin_fill()
walle.goto(5, 61)
walle.goto(5, 100)
walle.goto(-5, 100)
walle.goto(-5, 61)
walle.end_fill()
walle.penup()

walle.goto(4, 85)              # line - = head
walle.color('grey')
walle.begin_fill()
walle.pendown()
walle.goto(25, 80)
walle.goto(25, 110)
walle.goto(4, 115)
walle.goto(4, 85)
walle.end_fill()
walle.penup()
walle.goto(25, 80)
walle.begin_fill()
walle.pendown()
walle.circle(15)
walle.end_fill()
walle.penup()
walle.goto(-4, 85)
walle.begin_fill()
walle.pendown()
walle.goto(-25, 80)
walle.goto(-25, 110)
walle.goto(-4, 115)
walle.goto(-4, 85)
walle.end_fill()
walle.penup()
walle.goto(-25, 80)
walle.begin_fill()
walle.pendown()
walle.circle(15)
walle.end_fill()
walle.penup()

walle.goto(16, 86)             # line - = Eyes
walle.color('black')
walle.begin_fill()
walle.pendown()
walle.circle(10)
walle.end_fill()
walle.penup()
walle.goto(-16, 86)
walle.begin_fill()
walle.pendown()
walle.circle(10)
walle.end_fill()
walle.penup()

walle.goto(-10, -50)
walle.pendown()
walle.write('W A L L', font=("Arial", 10, "normal"))
walle.penup()
walle.goto(25, -44)
walle.begin_fill()
walle.pendown()
walle.circle(.25)
walle.end_fill()
walle.penup()
walle.goto(35, -50)
walle.color('red')
walle.begin_fill()
walle.circle(6)
walle.end_fill()
walle.penup()
walle.goto(32, -50)
walle.color('white')
walle.pendown()
walle.write('E', font=("Arial", 10, "normal"))

walle.penup()                  # line - = name at bottom
walle.color('black')
walle.goto(125, -100)
walle.pendown()
walle.write('Ian Neyens', font=("Arial", 10, "normal"))     # signs your name to your art
turtle.exitonclick()  # Keeps pycharm window open so we can see the drawing